name: VulnerableApp
options:
  bundleIdPrefix: com.security
targets:
  VulnerableApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    info:
      path: Info.plist
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
